---
# kubernetes/apps/database/cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: database
  labels:
    app: postgres-cluster
spec:
  instances: 3
  
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
  
  bootstrap:
    initdb:
      database: phoenix_app
      owner: app_user
      secret:
        name: postgres-credentials
  
  storage:
    size: 10Gi
    storageClass: local-path
  
  monitoring:
    enabled: true
    podMonitorEnabled: true
    customQueriesConfigMap:
      - name: postgresql-monitoring
        key: custom-queries.yaml
  
  postgresql:
    enableAlterSystem: true
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
