---
# kubernetes/apps/database/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: app_user
  password: secure-password-change-me
