---
# kubernetes/infrastructure/ingress-nginx/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.8.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  values:
    controller:
      service:
        type: NodePort
      nodeSelector:
        kubernetes.io/os: linux
      admissionWebhooks:
        enabled: true
        patch:
          nodeSelector:
            kubernetes.io/os: linux
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus
      config:
        use-proxy-protocol: "false"
        compute-full-forwarded-for: "true"
        use-forwarded-headers: "true"
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
